CYCAMORE: test_regression.TestRegression Class Reference
test_regression.TestRegression Class Reference
Public Member Functions
def __del__
def __init__
def teardown
def test_regression
Public Attributes
in_dir_
tmp_files_
Detailed Description
Definition at line 42 of file test_regression.py.
Constructor & Destructor Documentation
def test_regression.TestRegression.__init__ (self)
Definition at line 43 of file test_regression.py.
def test_regression.TestRegression.__del__ (self)
Definition at line 50 of file test_regression.py.
Member Function Documentation
def test_regression.TestRegression.teardown (self)
Definition at line 56 of file test_regression.py.
def test_regression.TestRegression.test_regression (self, check_deterministic = False)
Test for all inputs in sim_files. Checks if reference and current cyclus
output is the same.
Parameters
----------
check_deterministic : bool
    If True, also test determinisitc equality of simulations
WARNING: the tests require cyclus executable to be included in PATH
Definition at line 62 of file test_regression.py.
References cyclus_tools.compare_determ(), cyclus_tools.compare_nondeterm(), test_regression.TestRegression.in_dir_, cyclus_tools.run_cyclus(), and test_regression.TestRegression.tmp_files_.
Member Data Documentation
test_regression.TestRegression::in_dir_
Definition at line 43 of file test_regression.py.
Referenced by test_regression.TestRegression::test_regression().
test_regression.TestRegression::tmp_files_
Definition at line 43 of file test_regression.py.
Referenced by test_regression.TestRegression.test_regression().
The documentation for this class was generated from the following file:
test_regression.py