CYCAMORE: analysis Namespace Reference
analysis Namespace Reference
Functions
def collect
def determ_analysis
def main
def proxy_lst_to_dict
def report
Variables
string diff_col = """Column"""
string diff_tbl = """table is different"""
Function Documentation
def analysis.collect (args)
collects information on a determinisitic regression test run
Definition at line 15 of file analysis.py.
def analysis.determ_analysis (niter = 1000)
Calls deterministic regression tests for a number of iterations and reports
findings of nondeterminism to a file.
Parameters
----------
niter : int
      The number of times to run regression tests
fname : str
      The output filename to report to
Returns
-------
tbl_freq, col_freq : 2-tuple of dicts
                   tbl_freq is a frequency map of nondeterministic tables
                   col_freq is a frequency map of nondeterminisitc columns,
                   per table
Definition at line 47 of file analysis.py.
References proxy_lst_to_dict().
Referenced by main().
def analysis.main ()
Definition at line 133 of file analysis.py.
References determ_analysis(), and report().
def analysis.proxy_lst_to_dict (lst)
converts the col_freq list into a dictionary for easier processing
Definition at line 39 of file analysis.py.
Referenced by determ_analysis().
def analysis.report (tbl_freq, col_freq, fname = "report")
Prints the results of determ_analysis to a file
Parameters
----------
tbl_freq : dict
         the table frequency output from determ_analysis
col_freq : dict
         the column frequency output from determ_analysis
fname : str
      the output file name to print to
Definition at line 103 of file analysis.py.
Referenced by main().
Variable Documentation
string analysis::diff_col = """Column"""
Definition at line 13 of file analysis.py.
string analysis::diff_tbl = """table is different"""
Definition at line 12 of file analysis.py.