CYCAMORE: helper Namespace Reference
helper Namespace Reference
Functions
def create_sim_input
def exit_times
def find_ids
def hasher
def idx
def table_exist
Variables
tuple sha1array = lambdax:np.array(idx(hasher(x)), np.uint32)
Detailed Description
A set of tools for use in integration tests.
Function Documentation
def helper.create_sim_input (ref_input, k_factor_in, k_factor_out)
Creates xml input file from a reference xml input file.
Changes k_factor_in and k_factor_out in a simulation input
files for KFacility.
Args:
    ref_input: A reference xml input file with k_factors.
    k_factor_in: A new k_factor for requests.
    k_factor_out: A new conversion factor for offers.
Returns:
    A path to the created file. It is created in the same
    directory as the reference input file.
Definition at line 52 of file helper.py.
def helper.exit_times (agent_id, exit_table)
Finds exit times of the specified agent from the exit table.
Definition at line 40 of file helper.py.
def helper.find_ids (data, data_table, id_table)
Finds ids of the specified data located in the specified data_table,
and extracts the corresponding id from the specified id_table.
Definition at line 24 of file helper.py.
References sha1array.
Referenced by test_dynamic_capacitated.test_dynamic_capacitated(), and test_growth.test_growth().
def helper.hasher (x)
Definition at line 8 of file helper.py.
def helper.idx (h)
Definition at line 11 of file helper.py.
def helper.table_exist (db, tables)
Checks if hdf5 database contains the specified tables.
Definition at line 19 of file helper.py.
Referenced by test_dynamic_capacitated.test_dynamic_capacitated(), and test_growth.test_growth().
Variable Documentation
tuple helper::sha1array = lambdax:np.array(idx(hasher(x)), np.uint32)
Definition at line 17 of file helper.py.
Referenced by find_ids().