CYCAMORE: cyclus_tools Namespace Reference
cyclus_tools Namespace Reference
Functions
def compare_determ
def compare_nondeterm
def determ_err_msg
def run_cyclus
Function Documentation
def cyclus_tools.compare_determ (path1, path2, verbose = True)
Compares two Cyclus HDF5 databases assuming deterministic AgentIDs and
TransactionIDs
Returns
-------
rtn : bool
    True if both databases are identical other than their SimIDs
Definition at line 31 of file cyclus_tools.py.
References determ_err_msg().
Referenced by test_regression.TestRegression.test_regression().
def cyclus_tools.compare_nondeterm (path1, path2)
Compares two Cyclus HDF5 databases assuming non-deterministic AgentIDs
and TransactionIDs.
Returns
-------
rtn : bool
    True if both databases are the same, taking into account
    nondeterministic id assignments.
Definition at line 17 of file cyclus_tools.py.
Referenced by test_regression.TestRegression.test_regression().
def cyclus_tools.determ_err_msg (names, data_one, data_two)
Returns a string describing the deterministic difference between two
databases.
Definition at line 94 of file cyclus_tools.py.
Referenced by compare_determ().
def cyclus_tools.run_cyclus (cyclus, cwd, in_path, out_path)
Runs cyclus with various inputs and creates output databases
Definition at line 9 of file cyclus_tools.py.
References tools.check_cmd().
Referenced by create_references.main(), and test_regression.TestRegression.test_regression().