CYCAMORE: ref Namespace Reference
ref Namespace Reference
Functions
def add_main
def build_cycamore
def build_cyclus
def checkout
def decode_dbname
def encode_dbname
def fetch_refdbs
def gen_main
def prepare_repo
def push_rackspace
def repo_tags
def run_cyclus
Variables
tuple args = p.parse_args()
string desc = 'Generates cyclus reference databases for regression testing'
string help = 'force generate new ref-db rather than fetch remotely'
tuple p = argparse.ArgumentParser(description=desc)
tuple sub_add = subs.add_parser('add', help='add a new reference db set to the project')
tuple sub_gen = subs.add_parser('gen', help='create a new reference db set')
tuple subs = p.add_subparsers(help='sub-command help')
Function Documentation
def ref.add_main (args)
Definition at line 130 of file ref.py.
References decode_dbname(), and push_rackspace().
def ref.build_cycamore (build_path, install_path, prefix_path = '', boost = '', coin = '')
Definition at line 97 of file ref.py.
Referenced by gen_main().
def ref.build_cyclus (build_path, install_path, prefix_path = '', boost = '', coin = '')
Definition at line 81 of file ref.py.
Referenced by gen_main().
def ref.checkout (repo_path, commit)
Checks out the specified commit in a repo.
Definition at line 58 of file ref.py.
Referenced by gen_main().
def ref.decode_dbname (fname)
Definition at line 122 of file ref.py.
Referenced by add_main().
def ref.encode_dbname (cyclus_ref, cycamore_ref, input_file)
Definition at line 118 of file ref.py.
Referenced by run_cyclus().
def ref.fetch_refdbs (cyclus_ref, cycamore_ref, dst_path = '.')
Definition at line 171 of file ref.py.
def ref.gen_main (args)
Definition at line 17 of file ref.py.
References build_cycamore(), build_cyclus(), checkout(), prepare_repo(), repo_tags(), and run_cyclus().
def ref.prepare_repo (url, dst_path)
Clones a repo, creates a build dir.
Definition at line 50 of file ref.py.
Referenced by gen_main().
def ref.push_rackspace (fname, cred_file = 'rs.cred')
Definition at line 163 of file ref.py.
Referenced by add_main().
def ref.repo_tags (repo_path)
Returns a sorted list of all tags in the repo (most recent last).
Definition at line 66 of file ref.py.
Referenced by gen_main().
def ref.run_cyclus (install_path, input_file, cyclus_ref, cycamore_ref)
Definition at line 113 of file ref.py.
References encode_dbname().
Referenced by gen_main().
Variable Documentation
tuple ref::args = p.parse_args()
Definition at line 209 of file ref.py.
string ref::desc = 'Generates cyclus reference databases for regression testing'
Definition at line 177 of file ref.py.
string ref::help = 'force generate new ref-db rather than fetch remotely'
Definition at line 183 of file ref.py.
tuple ref::p = argparse.ArgumentParser(description=desc)
Definition at line 178 of file ref.py.
Referenced by cycamore::BatchReactor.GetMatlRequests(), cycamore::BatchReactor.phase(), TEST_F(), and cycamore.TEST_F().
tuple ref::sub_add = subs.add_parser('add', help='add a new reference db set to the project')
Definition at line 203 of file ref.py.
tuple ref::sub_gen = subs.add_parser('gen', help='create a new reference db set')
Definition at line 182 of file ref.py.
tuple ref::subs = p.add_subparsers(help='sub-command help')
Definition at line 179 of file ref.py.